apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs-hello
    version: blue  # Initial live version
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000